"""
load_data.py

LOAD step of the ETL pipeline.

Reads the CSVs generated by generate_data.py and bulk-loads them
into BOTH PostgreSQL and MySQL, in foreign-key dependency order.
Uses Pandas' to_sql() via SQLAlchemy, which handles batching
efficiently for tens of thousands of rows.

Requires schema to already exist in both databases -- run
schema/postgres/run_all_schema.sql and schema/mysql/run_all_schema.sql
first.

Credentials are read from environment variables, not hardcoded,
so real passwords never end up committed to Git. Set them before
running (PowerShell):
    $env:PG_PASSWORD = "your_postgres_password"
    $env:MYSQL_PASSWORD = "your_mysql_password"

Usage:
    python load_data.py --target postgres
    python load_data.py --target mysql
    python load_data.py --target both
"""

import argparse
import os
import pandas as pd
from sqlalchemy import create_engine

PG_PASSWORD = os.environ.get("PG_PASSWORD", "")
MYSQL_PASSWORD = os.environ.get("MYSQL_PASSWORD", "")

PG_CONN_STRING = f"postgresql+psycopg2://postgres:{PG_PASSWORD}@localhost:5432/sales_log"
MYSQL_CONN_STRING = f"mysql+pymysql://root:{MYSQL_PASSWORD}@localhost:3306/sales_log"

# Load order matters: parent tables before child tables that
# foreign-key reference them.
TABLES_IN_ORDER = [
    ("properties", "data/properties.csv"),
    ("agents", "data/agents.csv"),
    ("parties", "data/parties.csv"),
    ("transactions", "data/transactions.csv"),
    ("transaction_payments", "data/transaction_payments.csv"),
]


def load_into(engine, label: str):
    print(f"\n=== Loading into {label} ===")
    for table_name, csv_path in TABLES_IN_ORDER:
        df = pd.read_csv(csv_path)
        print(f"  Loading {len(df):>6} rows into {table_name}...")
        df.to_sql(
            table_name,
            engine,
            if_exists="append",   # schema already created the table structure
            index=False,
            chunksize=2000,        # batch inserts -- avoids one giant statement
            method="multi",        # multi-row INSERT statements, much faster than row-by-row
        )
    print(f"=== {label} load complete ===")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--target", choices=["postgres", "mysql", "both"], default="both")
    args = parser.parse_args()

    if args.target in ("postgres", "both"):
        pg_engine = create_engine(PG_CONN_STRING)
        load_into(pg_engine, "PostgreSQL")

    if args.target in ("mysql", "both"):
        mysql_engine = create_engine(MYSQL_CONN_STRING)
        load_into(mysql_engine, "MySQL")


if __name__ == "__main__":
    main()